### ISSUE TITLE
Update Node version to 16

### ISSUE THREAD

**Issue by weotch** [BKWLD/cloak-boilerplate#23]
- [ ] Update .nvmrc
- [ ] Add this to Netlify.toml to be explicit

```toml
# Set Node version (Netlify doesn't respect monorepo's .nvmrc)
[build.environment]
	NODE_VERSION = '16'
```
